### ISSUE TITLE
`wireplumber::pw::Link::state()` panics when error is `null`

### ISSUE THREAD

**Issue by Ryuukyu313** [arcnmx/wireplumber.rs#6]
[`wireplumber::pw::Link::state()`](https://arcnmx.github.io/wireplumber.rs/wireplumber/pw/struct.Link.html#method.state) panics for me when the returned error is null:

```
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /var/home/tomwagner/Projects/pipewire/helvum/debug/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.2/src/gstring.rs:787:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: <glib::gstring::GString as glib::translate::FromGlibPtrNone<*const u8>>::from_glib_none
             at ./cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.2/src/gstring.rs:787:9
   4: glib::translate::from_glib_none
             at ./cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.2/src/translate.rs:1459:5
   5: <glib::gstring::GString as glib::translate::FromGlibPtrNone<*const i8>>::from_glib_none
             at ./cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.2/src/gstring.rs:798:9
   6: glib::translate::from_glib_none
             at ./cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.2/src/translate.rs:1459:5
   7: wireplumber::auto::link::Link::state
             at ./cargo-home/git/checkouts/wireplumber.rs-cb0425781db64edb/73bc32e/src/auto/link.rs:73:19
...
```

The out parameter for the error is [marked as optional ](https://pipewire.pages.freedesktop.org/wireplumber/c_api/link_api.html#c.wp_link_get_state) but it seems the bindings assume it is not.

**Comment by Ryuukyu313** [comment]
Just in case anyone is looking for a workaround, using `link.property::<wp::pw::LinkState>("state")` works fine.
